# Generated by Django 5.2 on 2025-05-06 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
        ('blogs', '0004_alter_bloglike_blog_alter_bloglike_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='adminpanel.category'),
        ),
    ]
