# Generated by Django 5.2 on 2025-05-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blogs_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('pending', 'Pending'), ('archived', 'Archived')], default='draft', max_length=10),
        ),
    ]
